### ISSUE TITLE
The elevator is missing the "maincomputer" script 

### ISSUE THREAD

**Issue by QuillLittlefeather** [acidphyx/OpenSim#1]
Can you please help me with setting up the elevator and where is the Maincomputer script. also when i change door to open on axis x it still only opens on axis y

**Comment by acidphyx** [comment]
Thanks for the info. :-) I have contacted you in-world and am willing to work you through any issues you are having. As for the "Main Computer" Script. If I remember right the elevator talks to a control panel. So the Main Computer is the Control Panel Script. Once I confirm this I will post the full results and if needed post any coded updates for everyone.
